version: "{build}"

os: Windows Server 2012 R2
platform:
  - x64

# Environment variables can be overridden in the Appveyor's build
# settings. A more secure password should be set there.
environment:
  winrm_user: kitchen_user
  winrm_pass: p@ssw0rd
  winrm_port: 5985
  KITCHEN_YAML: .kitchen.appveyor.yml

  matrix:
    - ruby_version: "23"

clone_depth: 1

install:
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: gem install bundler --quiet --no-ri --no-rdoc
  - ps: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\salt-jenkins\certs.pem
  - ps: Invoke-WebRequest -Uri https://gist.githubusercontent.com/dwoz/b9553ae70f4407d8dcad86ceb34d5fd4/raw/0926ef47e1759b2733dd1415f3f402429c0dd317/install-openssh.ps1 -OutFile c:\install_openssh.ps1
  - set SSL_CERT_FILE=c:\projects\salt-jenkins\certs.pem

build_script:
  - bundle install --with windows

test_script:
  - ps: >-
     if ($env:DEBUG_BUILD -eq "yes") {
         bundle exec kitchen verify windows -l debug | tee kitchen.run.log
     } else {
         bundle exec kitchen verify windows | tee kitchen.run.log
     }

on_failure:
  - ps: ls ./*
  - bundle exec kitchen diagnose --all
  - ps: Get-ChildItem ".\\.kitchen\\logs\\kitchen.log" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem "kitchen.run.log" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
