language: ruby
services:
  - docker
rvm:
  - ruby
dist: trusty
env:
  matrix:
    - SUITE=centos-7
    - SUITE=centos-6
    - SUITE=fedora
    - SUITE=py2-ubuntu-16
    - SUITE=py3-ubuntu-16
    - SUITE=ubuntu-rolling
    - SUITE=debian-8
    - SUITE=debian-9
    - SUITE=opensuse
    - SUITE=arch
bundler_args: --without windows
script:
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 2
  # Provision containers
  - bundle exec kitchen converge $SUITE
after_script:
  - bundle exec kitchen list $SUITE
  - bundle exec kitchen destroy $SUITE
matrix:
  allow_failures:
    - env: SUITE=opensuse
